export default function Home() {

    return (
        <div className="home">
            <h1>Home Body</h1>
            <p id="about" className="lorem">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a urna mauris. Donec et sem nulla. Sed ultrices ornare nisl. Morbi non leo fermentum, efficitur purus at, laoreet enim. Aenean accumsan arcu arcu, nec ornare nunc porta varius. Cras mauris sapien, scelerisque eget neque eget, congue ullamcorper risus. Fusce condimentum lectus accumsan enim commodo suscipit. Duis et turpis aliquet, venenatis urna aliquam, ultrices nisi. Mauris arcu tellus, fringilla a luctus quis, aliquet ultrices arcu. Nam tempor augue vitae egestas vestibulum. Nam et diam enim. Aenean pellentesque tempus erat. Sed tristique ligula malesuada, pharetra ligula vitae, scelerisque lorem. Fusce placerat diam molestie purus venenatis faucibus. Maecenas eget mattis arcu, eu aliquet quam.

Quisque nunc arcu, congue vel consectetur a, efficitur blandit purus. Proin nec vulputate purus, quis ullamcorper urna. Sed ac ex id mi auctor laoreet. Duis varius placerat nisl vel dapibus. Morbi pellentesque in nunc in efficitur. Ut malesuada odio commodo, cursus augue at, facilisis ante. Aliquam a vestibulum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum a nibh rhoncus, dictum nunc eu, blandit ante. Donec placerat efficitur felis. Suspendisse eget efficitur lectus. Donec auctor est quis ligula dapibus, sed laoreet ligula egestas. Maecenas et justo nec ex sodales fringilla. Maecenas quis ex at odio pretium suscipit. Phasellus arcu lacus, mattis vitae dignissim vitae, venenatis sed neque. Vivamus facilisis, nulla id faucibus ultricies, est odio fringilla lacus, a pharetra nibh orci at tortor.

Etiam luctus mi et accumsan viverra. Quisque a dignissim nisl, vitae interdum eros. Mauris finibus eros lorem, vitae ullamcorper neque tincidunt non. Donec semper, nisl a molestie pellentesque, mi tortor ultrices nulla, ac laoreet lorem lacus vel tortor. Curabitur semper pretium lectus ac dictum. Nunc posuere turpis velit, at commodo tortor pulvinar sit amet. Morbi vitae ultrices diam. Sed sit amet luctus magna, eget auctor massa. Phasellus vel dignissim ex. Etiam vel scelerisque ipsum. Suspendisse velit libero, porta id dui non, posuere fermentum nulla. Suspendisse pulvinar urna et dictum lacinia. Integer viverra nisi libero, sit amet fringilla lacus aliquet rhoncus. Sed dapibus purus massa, eget pharetra lacus posuere nec. Fusce sollicitudin massa vitae sem finibus, semper feugiat sapien elementum. Sed porta erat sed venenatis finibus.

Integer commodo interdum sem. Aenean quis gravida arcu. In sit amet magna interdum, facilisis urna quis, suscipit augue. Quisque tincidunt, mi at vulputate dictum, nisi ligula semper orci, eget tincidunt nisi risus id erat. In vel nibh ut augue eleifend rhoncus eget ullamcorper massa. Integer neque diam, viverra molestie commodo in, vehicula id felis. In sit amet ligula id quam sollicitudin auctor a nec ligula. Vivamus sodales, dolor ut imperdiet volutpat, ipsum magna blandit nisi, quis ullamcorper quam nisl quis ex. Morbi pellentesque vulputate lacus, sit amet vestibulum augue pellentesque nec. Nulla in venenatis dui, in aliquet risus. Integer fermentum turpis dapibus dolor luctus, sit amet luctus massa pulvinar. Aliquam erat volutpat. Vestibulum eleifend egestas aliquam. Fusce accumsan elit dolor, id iaculis est porta non. Sed venenatis orci ex, sit amet sodales nulla rutrum vitae.

Pellentesque ac cursus ex. Proin quis justo non metus tincidunt posuere at id sem. Vestibulum facilisis ipsum non facilisis sagittis. Vivamus convallis venenatis iaculis. In enim sem, eleifend a odio sed, vulputate consectetur ex. Aliquam erat volutpat. Morbi vitae viverra velit. Maecenas porta venenatis ligula, eget mattis erat. Fusce nulla est, finibus ut diam vel, mattis rutrum tortor. Curabitur vitae leo blandit, commodo augue sit amet, fringilla mi. Aliquam auctor augue non nulla cursus finibus. Aenean efficitur velit in elit venenatis, non fermentum elit efficitur. Vestibulum posuere, metus at vehicula hendrerit, nunc justo finibus erat, in aliquam sapien metus eu mauris. Ut dapibus diam vitae consequat ornare. Vestibulum finibus, tortor ac auctor pulvinar, ligula lacus dictum felis, vitae maximus quam felis pellentesque urna.</p>
            <p id="skills" className="lorem">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a urna mauris. Donec et sem nulla. Sed ultrices ornare nisl. Morbi non leo fermentum, efficitur purus at, laoreet enim. Aenean accumsan arcu arcu, nec ornare nunc porta varius. Cras mauris sapien, scelerisque eget neque eget, congue ullamcorper risus. Fusce condimentum lectus accumsan enim commodo suscipit. Duis et turpis aliquet, venenatis urna aliquam, ultrices nisi. Mauris arcu tellus, fringilla a luctus quis, aliquet ultrices arcu. Nam tempor augue vitae egestas vestibulum. Nam et diam enim. Aenean pellentesque tempus erat. Sed tristique ligula malesuada, pharetra ligula vitae, scelerisque lorem. Fusce placerat diam molestie purus venenatis faucibus. Maecenas eget mattis arcu, eu aliquet quam.

Quisque nunc arcu, congue vel consectetur a, efficitur blandit purus. Proin nec vulputate purus, quis ullamcorper urna. Sed ac ex id mi auctor laoreet. Duis varius placerat nisl vel dapibus. Morbi pellentesque in nunc in efficitur. Ut malesuada odio commodo, cursus augue at, facilisis ante. Aliquam a vestibulum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum a nibh rhoncus, dictum nunc eu, blandit ante. Donec placerat efficitur felis. Suspendisse eget efficitur lectus. Donec auctor est quis ligula dapibus, sed laoreet ligula egestas. Maecenas et justo nec ex sodales fringilla. Maecenas quis ex at odio pretium suscipit. Phasellus arcu lacus, mattis vitae dignissim vitae, venenatis sed neque. Vivamus facilisis, nulla id faucibus ultricies, est odio fringilla lacus, a pharetra nibh orci at tortor.

Etiam luctus mi et accumsan viverra. Quisque a dignissim nisl, vitae interdum eros. Mauris finibus eros lorem, vitae ullamcorper neque tincidunt non. Donec semper, nisl a molestie pellentesque, mi tortor ultrices nulla, ac laoreet lorem lacus vel tortor. Curabitur semper pretium lectus ac dictum. Nunc posuere turpis velit, at commodo tortor pulvinar sit amet. Morbi vitae ultrices diam. Sed sit amet luctus magna, eget auctor massa. Phasellus vel dignissim ex. Etiam vel scelerisque ipsum. Suspendisse velit libero, porta id dui non, posuere fermentum nulla. Suspendisse pulvinar urna et dictum lacinia. Integer viverra nisi libero, sit amet fringilla lacus aliquet rhoncus. Sed dapibus purus massa, eget pharetra lacus posuere nec. Fusce sollicitudin massa vitae sem finibus, semper feugiat sapien elementum. Sed porta erat sed venenatis finibus.

Integer commodo interdum sem. Aenean quis gravida arcu. In sit amet magna interdum, facilisis urna quis, suscipit augue. Quisque tincidunt, mi at vulputate dictum, nisi ligula semper orci, eget tincidunt nisi risus id erat. In vel nibh ut augue eleifend rhoncus eget ullamcorper massa. Integer neque diam, viverra molestie commodo in, vehicula id felis. In sit amet ligula id quam sollicitudin auctor a nec ligula. Vivamus sodales, dolor ut imperdiet volutpat, ipsum magna blandit nisi, quis ullamcorper quam nisl quis ex. Morbi pellentesque vulputate lacus, sit amet vestibulum augue pellentesque nec. Nulla in venenatis dui, in aliquet risus. Integer fermentum turpis dapibus dolor luctus, sit amet luctus massa pulvinar. Aliquam erat volutpat. Vestibulum eleifend egestas aliquam. Fusce accumsan elit dolor, id iaculis est porta non. Sed venenatis orci ex, sit amet sodales nulla rutrum vitae.

Pellentesque ac cursus ex. Proin quis justo non metus tincidunt posuere at id sem. Vestibulum facilisis ipsum non facilisis sagittis. Vivamus convallis venenatis iaculis. In enim sem, eleifend a odio sed, vulputate consectetur ex. Aliquam erat volutpat. Morbi vitae viverra velit. Maecenas porta venenatis ligula, eget mattis erat. Fusce nulla est, finibus ut diam vel, mattis rutrum tortor. Curabitur vitae leo blandit, commodo augue sit amet, fringilla mi. Aliquam auctor augue non nulla cursus finibus. Aenean efficitur velit in elit venenatis, non fermentum elit efficitur. Vestibulum posuere, metus at vehicula hendrerit, nunc justo finibus erat, in aliquam sapien metus eu mauris. Ut dapibus diam vitae consequat ornare. Vestibulum finibus, tortor ac auctor pulvinar, ligula lacus dictum felis, vitae maximus quam felis pellentesque urna.</p>
            <p id="projects" className="lorem">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a urna mauris. Donec et sem nulla. Sed ultrices ornare nisl. Morbi non leo fermentum, efficitur purus at, laoreet enim. Aenean accumsan arcu arcu, nec ornare nunc porta varius. Cras mauris sapien, scelerisque eget neque eget, congue ullamcorper risus. Fusce condimentum lectus accumsan enim commodo suscipit. Duis et turpis aliquet, venenatis urna aliquam, ultrices nisi. Mauris arcu tellus, fringilla a luctus quis, aliquet ultrices arcu. Nam tempor augue vitae egestas vestibulum. Nam et diam enim. Aenean pellentesque tempus erat. Sed tristique ligula malesuada, pharetra ligula vitae, scelerisque lorem. Fusce placerat diam molestie purus venenatis faucibus. Maecenas eget mattis arcu, eu aliquet quam.

Quisque nunc arcu, congue vel consectetur a, efficitur blandit purus. Proin nec vulputate purus, quis ullamcorper urna. Sed ac ex id mi auctor laoreet. Duis varius placerat nisl vel dapibus. Morbi pellentesque in nunc in efficitur. Ut malesuada odio commodo, cursus augue at, facilisis ante. Aliquam a vestibulum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum a nibh rhoncus, dictum nunc eu, blandit ante. Donec placerat efficitur felis. Suspendisse eget efficitur lectus. Donec auctor est quis ligula dapibus, sed laoreet ligula egestas. Maecenas et justo nec ex sodales fringilla. Maecenas quis ex at odio pretium suscipit. Phasellus arcu lacus, mattis vitae dignissim vitae, venenatis sed neque. Vivamus facilisis, nulla id faucibus ultricies, est odio fringilla lacus, a pharetra nibh orci at tortor.

Etiam luctus mi et accumsan viverra. Quisque a dignissim nisl, vitae interdum eros. Mauris finibus eros lorem, vitae ullamcorper neque tincidunt non. Donec semper, nisl a molestie pellentesque, mi tortor ultrices nulla, ac laoreet lorem lacus vel tortor. Curabitur semper pretium lectus ac dictum. Nunc posuere turpis velit, at commodo tortor pulvinar sit amet. Morbi vitae ultrices diam. Sed sit amet luctus magna, eget auctor massa. Phasellus vel dignissim ex. Etiam vel scelerisque ipsum. Suspendisse velit libero, porta id dui non, posuere fermentum nulla. Suspendisse pulvinar urna et dictum lacinia. Integer viverra nisi libero, sit amet fringilla lacus aliquet rhoncus. Sed dapibus purus massa, eget pharetra lacus posuere nec. Fusce sollicitudin massa vitae sem finibus, semper feugiat sapien elementum. Sed porta erat sed venenatis finibus.

Integer commodo interdum sem. Aenean quis gravida arcu. In sit amet magna interdum, facilisis urna quis, suscipit augue. Quisque tincidunt, mi at vulputate dictum, nisi ligula semper orci, eget tincidunt nisi risus id erat. In vel nibh ut augue eleifend rhoncus eget ullamcorper massa. Integer neque diam, viverra molestie commodo in, vehicula id felis. In sit amet ligula id quam sollicitudin auctor a nec ligula. Vivamus sodales, dolor ut imperdiet volutpat, ipsum magna blandit nisi, quis ullamcorper quam nisl quis ex. Morbi pellentesque vulputate lacus, sit amet vestibulum augue pellentesque nec. Nulla in venenatis dui, in aliquet risus. Integer fermentum turpis dapibus dolor luctus, sit amet luctus massa pulvinar. Aliquam erat volutpat. Vestibulum eleifend egestas aliquam. Fusce accumsan elit dolor, id iaculis est porta non. Sed venenatis orci ex, sit amet sodales nulla rutrum vitae.

Pellentesque ac cursus ex. Proin quis justo non metus tincidunt posuere at id sem. Vestibulum facilisis ipsum non facilisis sagittis. Vivamus convallis venenatis iaculis. In enim sem, eleifend a odio sed, vulputate consectetur ex. Aliquam erat volutpat. Morbi vitae viverra velit. Maecenas porta venenatis ligula, eget mattis erat. Fusce nulla est, finibus ut diam vel, mattis rutrum tortor. Curabitur vitae leo blandit, commodo augue sit amet, fringilla mi. Aliquam auctor augue non nulla cursus finibus. Aenean efficitur velit in elit venenatis, non fermentum elit efficitur. Vestibulum posuere, metus at vehicula hendrerit, nunc justo finibus erat, in aliquam sapien metus eu mauris. Ut dapibus diam vitae consequat ornare. Vestibulum finibus, tortor ac auctor pulvinar, ligula lacus dictum felis, vitae maximus quam felis pellentesque urna.</p>
            <p id="contact" className="lorem">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a urna mauris. Donec et sem nulla. Sed ultrices ornare nisl. Morbi non leo fermentum, efficitur purus at, laoreet enim. Aenean accumsan arcu arcu, nec ornare nunc porta varius. Cras mauris sapien, scelerisque eget neque eget, congue ullamcorper risus. Fusce condimentum lectus accumsan enim commodo suscipit. Duis et turpis aliquet, venenatis urna aliquam, ultrices nisi. Mauris arcu tellus, fringilla a luctus quis, aliquet ultrices arcu. Nam tempor augue vitae egestas vestibulum. Nam et diam enim. Aenean pellentesque tempus erat. Sed tristique ligula malesuada, pharetra ligula vitae, scelerisque lorem. Fusce placerat diam molestie purus venenatis faucibus. Maecenas eget mattis arcu, eu aliquet quam.

Quisque nunc arcu, congue vel consectetur a, efficitur blandit purus. Proin nec vulputate purus, quis ullamcorper urna. Sed ac ex id mi auctor laoreet. Duis varius placerat nisl vel dapibus. Morbi pellentesque in nunc in efficitur. Ut malesuada odio commodo, cursus augue at, facilisis ante. Aliquam a vestibulum velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum a nibh rhoncus, dictum nunc eu, blandit ante. Donec placerat efficitur felis. Suspendisse eget efficitur lectus. Donec auctor est quis ligula dapibus, sed laoreet ligula egestas. Maecenas et justo nec ex sodales fringilla. Maecenas quis ex at odio pretium suscipit. Phasellus arcu lacus, mattis vitae dignissim vitae, venenatis sed neque. Vivamus facilisis, nulla id faucibus ultricies, est odio fringilla lacus, a pharetra nibh orci at tortor.

Etiam luctus mi et accumsan viverra. Quisque a dignissim nisl, vitae interdum eros. Mauris finibus eros lorem, vitae ullamcorper neque tincidunt non. Donec semper, nisl a molestie pellentesque, mi tortor ultrices nulla, ac laoreet lorem lacus vel tortor. Curabitur semper pretium lectus ac dictum. Nunc posuere turpis velit, at commodo tortor pulvinar sit amet. Morbi vitae ultrices diam. Sed sit amet luctus magna, eget auctor massa. Phasellus vel dignissim ex. Etiam vel scelerisque ipsum. Suspendisse velit libero, porta id dui non, posuere fermentum nulla. Suspendisse pulvinar urna et dictum lacinia. Integer viverra nisi libero, sit amet fringilla lacus aliquet rhoncus. Sed dapibus purus massa, eget pharetra lacus posuere nec. Fusce sollicitudin massa vitae sem finibus, semper feugiat sapien elementum. Sed porta erat sed venenatis finibus.

Integer commodo interdum sem. Aenean quis gravida arcu. In sit amet magna interdum, facilisis urna quis, suscipit augue. Quisque tincidunt, mi at vulputate dictum, nisi ligula semper orci, eget tincidunt nisi risus id erat. In vel nibh ut augue eleifend rhoncus eget ullamcorper massa. Integer neque diam, viverra molestie commodo in, vehicula id felis. In sit amet ligula id quam sollicitudin auctor a nec ligula. Vivamus sodales, dolor ut imperdiet volutpat, ipsum magna blandit nisi, quis ullamcorper quam nisl quis ex. Morbi pellentesque vulputate lacus, sit amet vestibulum augue pellentesque nec. Nulla in venenatis dui, in aliquet risus. Integer fermentum turpis dapibus dolor luctus, sit amet luctus massa pulvinar. Aliquam erat volutpat. Vestibulum eleifend egestas aliquam. Fusce accumsan elit dolor, id iaculis est porta non. Sed venenatis orci ex, sit amet sodales nulla rutrum vitae.

Pellentesque ac cursus ex. Proin quis justo non metus tincidunt posuere at id sem. Vestibulum facilisis ipsum non facilisis sagittis. Vivamus convallis venenatis iaculis. In enim sem, eleifend a odio sed, vulputate consectetur ex. Aliquam erat volutpat. Morbi vitae viverra velit. Maecenas porta venenatis ligula, eget mattis erat. Fusce nulla est, finibus ut diam vel, mattis rutrum tortor. Curabitur vitae leo blandit, commodo augue sit amet, fringilla mi. Aliquam auctor augue non nulla cursus finibus. Aenean efficitur velit in elit venenatis, non fermentum elit efficitur. Vestibulum posuere, metus at vehicula hendrerit, nunc justo finibus erat, in aliquam sapien metus eu mauris. Ut dapibus diam vitae consequat ornare. Vestibulum finibus, tortor ac auctor pulvinar, ligula lacus dictum felis, vitae maximus quam felis pellentesque urna.</p>
        </div>
    )
}